name: miraca
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - numpy>=1.26
  - pip
  - pandas>=2.2
  - geopandas>=0.14
  - scipy
  - shapely>=2.0
  - rasterio
  - rioxarray
  - networkx
  - osmnx
  - python-igraph=0.11.*
  - snkit
  - xarray
  - pydeck
  - pyarrow
  - tqdm
  - openpyxl>=3.1
  - rtree
  - rasterstats
  - contextily
  - numba>=0.59
  - matplotlib>=3.8
  - plotly>=5.9
  - ipykernel
  - jupyter
  - pytest
  - black
  - ruff
  - lonboard
  - cartopy
  - pandapower

  - pip:
      - damagescanner==1.0.0
      - ema_workbench
      - "-e ."
      - git+https://github.com/nismod/DAFNI-NIRD.git
      - -e ./miraca-book/background/RoadFlowModelling
      - -e ./miraca-book/background/CBAmodelling
